from django.urls import path
from app.views import (
  index,
  PostListView,
  post_detail,
  PostCreateView,
  post_edit,
  PostEditView,
  post_delete,
  PostDeleteView,
  UserProfileView,
  UserProfileRelationsView,
  UserProfileUpdateView,
  comment_create,
  CommentCreateView,
  CommentEditView,
  CommentDeleteView,
  accept_friend_request,
  AcceptFriendRequestView,
  reject_friend_request,
  cancel_friend_request,
  SendFriendRequestView,
  UnfriendView,
  RegisterView,
  LoginView,
  LogoutView,
)

urlpatterns = [
  path('', index, name='post_list'),
  path('', PostListView.as_view(), name='post_list'),
  path('register/', RegisterView.as_view(), name='register'),
  path('login/', LoginView.as_view(), name='login'),
  path('logout/', LogoutView.as_view(), name='logout'),
  path('post/<int:pk>', post_detail, name='post_detail'),
  path('post/create', PostCreateView.as_view(), name='post_create'),
  path('post/<int:pk>/edit', post_edit, name='post_edit'),
  path('post/<int:pk>/edit', PostEditView.as_view(), name='post_edit'),
  path('post/<int:pk>/delete', post_delete, name='post_delete'),
  path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post_delete'),
  path('post/<int:pk>/comment/create', comment_create, name='comment_create'),
  path('post/<int:pk>/comment/create', CommentCreateView.as_view(), name='comment_create'),
  path('post/<int:pk>/comment/<int:pk_comment>/edit', CommentEditView.as_view(), name='comment_edit'),
  path('post/<int:pk>/comment/<int:pk_comment>/delete', CommentDeleteView.as_view(), name='comment_delete'),
  path('userprofile/<int:pk>', UserProfileView.as_view(), name='user_profile'),
  path('userprofile/<int:pk>/relations', UserProfileRelationsView.as_view(), name='user_profile_relations'),
  path('userprofile/<int:pk>/edit', UserProfileUpdateView.as_view(), name='user_profile_edit'),
  # friends management
  # path('accept_friend_request/<int:user_pk>', accept_friend_request, name='accept_friend_request'),
  path('accept_friend_request/<int:user_pk>', AcceptFriendRequestView.as_view(), name='accept_friend_request'),
  path('reject_friend_request/<int:user_pk>', reject_friend_request, name='reject_friend_request'),
  path('cancel_friend_request/<int:user_pk>', cancel_friend_request, name='cancel_friend_request'),
  path('unfriend/<int:friend_pk>', UnfriendView.as_view(), name='unfriend'),
  path('send_friend_request/<int:user_pk>', SendFriendRequestView.as_view(), name='send_friend_request'),
]
